env:
    global:
        - PACKAGE="JavaScript Enhancements"
        - SUBLIME_TEXT_VERSION="3"

matrix:
    include:
        - os: linux
          language: python
          python: 3.3
        - os: osx
          language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/pichillilorenzo/JavaScriptEnhancements/master/sbin/travis.sh
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
            /etc/init.d/xvfb -screen 0 1024x768x24 +extension RANDR;
      fi

install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew upgrade python;
      fi
    - sh travis.sh bootstrap
    - sh travis.sh install_color_scheme_unit
    - sh travis.sh install_keypress
    - sh travis.sh install_terminal_view_package

script:
    - sh travis.sh run_tests --coverage

after_success:
    - pip3 install codecov;
    - codecov

notifications:
    email: false